variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  IMAGE_NAME: my-torquehub-api  # Name for your Docker image

stages:
  - build
  - test
  - docker_build

# Build Stage
build:
  stage: build
  script:
    # Assemble the project using Gradle (this generates the JAR file)
    - ./gradlew assemble

# Test Stage
test:
  stage: test
  script:
    # Run tests using Gradle
    - ./gradlew test

# Docker Build and Run Stage
docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind  # Enable Docker in Docker to build the image
  before_script:
    - docker info  # Verify Docker service is available
  script:
    # Build the Docker image for TorqueHub using the Dockerfile provided
    - docker build -t $IMAGE_NAME:latest .

    # Optional: Run the Docker container to ensure it works correctly
    - docker run -d -p 8090:8080 $IMAGE_NAME:latest
