# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
  
stages: 
  - build 
  - test
  - docker_build

build: 
  stage: build 
  script: 
  - ./gradlew assemble
  artifacts:
    # Store the JAR file as an artifact for later stages
    paths:
      - build/libs/TorqueHub-0.0.1-SNAPSHOT.jar

test: 
  stage: test 
  script: 
    - ./gradlew test


docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # Check Docker setup
    - docker info
  script:
    # Build the Docker image using the Dockerfile in your project
    - docker build -t torquehub-api .
    # Run the Docker container, exposing the internal port 8080 as 8090 on the host
    - docker run -d -p 8090:8080 torquehub-api
  only:
    # Specify that the docker build stage runs only on the 'main' branch
    - main