variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  IMAGE_NAME: torquehub-api  # Name for your Docker image

stages:
  - build
  - test
  - docker_build

# Build Stage: Compile the project
build:
  stage: build
  script:
    - ./gradlew assemble

# Test Stage: Run tests
test:
  stage: test
  script:
    - ./gradlew test

# Docker Build Stage: Build and optionally run the Docker image
docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info  # Check Docker service is running
  script:
    # Force Docker to use the regular docker build command
    - /usr/bin/docker build -t $IMAGE_NAME:latest .

    # Optionally, run the container to verify it works
    - docker run -d -p 8090:8080 $IMAGE_NAME:latest
